### ISSUE TITLE
API simplification tracking issue

### ISSUE THREAD

**Issue by obmarg** [obmarg/graphql-ws-client#59]
I'm not very happy with the API of graphql-ws-client at the moment:

1. Too many generic parameters everywhere
2. Integrating into new clients takes too much boilerplate
3. Dropping connections when the client drops makes sense but is... kind of surprising.  It's not how most other clients work for example.

Plans to fix:

- [x] Remove the `GraphqlClient` trait https://github.com/obmarg/graphql-ws-client/pull/58
- [x] Possibly get rid of `WsMessage` as a generic param on the `AsyncWebsocketClient` https://github.com/obmarg/graphql-ws-client/pull/61
  - [x] Want to expose something that transforms generic type to a concrete internal type.  new function remains generic but the output won't be.
  - [x] Could maybe combine send & sink into a single parameter w/ impls for splittable streams etc?  Not sure, need to toy with it and see what is most ergonomic.
- [x] Try to get rid of the `runtime: impl SpawnExt` parameter - could just return a future and let users deal with it instead.  Probably less code in the end. https://github.com/obmarg/graphql-ws-client/pull/61
- [x] Change the drop behaviour - clients _and_ subscriptions should both keep the receiver_loop running, assuming the user has spawned it somewhere persistent.  If the user wants the old behaviour they drop the returned future. https://github.com/obmarg/graphql-ws-client/pull/61
- [x] Add a method to subscription streams that takes the connection future and runs it inside the stream, to handle the common case of wanting to run a single subscription per connection. https://github.com/obmarg/graphql-ws-client/pull/65
  - [x] Discovered while trying this in a project that you still need to run the actor while making the subscription.  It's a bit clumsy, may need more thought.
- [x] While I'm going nuts - is `AsyncWebsocketClient` the best name?  Not sure (not super keen to go changing that though) https://github.com/obmarg/graphql-ws-client/pull/61
- [x] Update the various websocket impls
  - [x] async tungstenite https://github.com/obmarg/graphql-ws-client/pull/62
  - [x] ws-stream-wasm https://github.com/obmarg/graphql-ws-client/pull/64
- [x] Module tidy up https://github.com/obmarg/graphql-ws-client/pull/67
   - [x] Move stuff out of the `next` module
   - [x] Remove the allow(unused) https://github.com/obmarg/graphql-ws-client/pull/68
   - [x] Deprecate old interface
- [x] Document new stuff (including doctests)
- [x] Update the examples to use the new API 
- [x] Remove the default feature on async tungstenite https://github.com/obmarg/graphql-ws-client/pull/69
- [x] Make graphql_client example & test
- [x] Make a release candidate

### Post Release Candidate 

Can solicit feedback with release candidate and decide on these:

- [ ] API concerns
   - [ ] ~Think about whether client::streaming_operation _needs_ a `&mut self`~
   - [ ] Think about whether I even need the ping/pong messages
   - [ ] `run` function vs `IntoFuture`

**Comment by Sytten** [comment]
I agree with most of the changes, though the serde value seems like a regression in terms of quality when we know the type that would be returned for each client.

Returning a future for the client to drive the connection is generally a good idea, that seems to be the pattern adopted by most.

**Comment by obmarg** [comment]
Thanks for the input @Sytten - hoped you'd see this.

> the serde value seems like a regression in terms of quality when we know the type that would be returned for each client.

We weren't doing anything useful with the `GenericResponse` in `graphql-ws-client`, and by moving the responsibility for deserialisation fully into `StreamingOperation::decode_response` we can get rid of a trait and simplify a lot of generics.

I don't see much benefit to having that additional phase of deserialisation, and from a users perspective it functions the same as it did before.  Happy to consider rolling it back if there's something I'm missing though?

**Comment by Sytten** [comment]
Ha its been a while since I looked at the code so I trust it will be a good change.

**Comment by obmarg** [comment]
@Sytten [v0.8.0-rc.1](https://github.com/obmarg/graphql-ws-client/releases/tag/v0.8.0-rc.1) is out now if you want to try upgrading.  I'd love to hear any feedback you might have
